# Generated by Django 5.1.1 on 2024-10-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Category',
            new_name='category',
        ),
    ]
